# Secrets partagés entre agent et front
apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:
  LIVEKIT_API_KEY: "${LIVEKIT_API_KEY}"
  LIVEKIT_API_SECRET: "${LIVEKIT_API_SECRET}"

---
# Secrets spécifiques à l'agent
apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
type: Opaque
stringData:
  CARTESIA_API_KEY: "${CARTESIA_API_KEY}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  DEEPGRAM_API_KEY: "${DEEPGRAM_API_KEY}"