apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
        component: backend
    spec:
      # Give the agent 10 minutes to finish up any ongoing conversations
      terminationGracePeriodSeconds: 600
      containers:
      - name: agent
        image: scenaro-voice-agent
        ports:
        - name: livekit
          containerPort: 7880
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: shared-config
        - configMapRef:
            name: agent-config
        - secretRef:
            name: shared-secrets
        - secretRef:
            name: agent-secrets
        # Variables d'environnement via envFrom seulement
        resources:
          requests:
            cpu: 1700m # 4 is minimum recommended
            memory: 6Gi # 8Gi is minimum recommended
          limits:
            cpu: 1700m # 4 is minimum recommended
            memory: 7Gi  # 8Gi is minimum recommended
        livenessProbe:
          httpGet:
            path: /api/sys/status/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/sys/status/ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
      securityContext:
        fsGroup: 1001