apiVersion: v1
kind: Service
metadata:
  name: agent-service
  labels:
    app: agent
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 7880
    targetPort: 7880
    protocol: TCP
    name: http
  selector:
    app: agent